[package]
name = "spudlib"
version = "0.1.0"
edition = "2021"
description = "Safe idiomatic Rust bindings to SpudLib"
license = "MIT"
repository = "https://github.com/vigatel2717/spudlib"

[dependencies]
spudlib-sys = { path = "../spudlib-sys", version = "0.1.0" }

[features]
default = ["vulkan"]
vulkan = ["spudlib-sys/vulkan"]
metal = ["spudlib-sys/metal"]

[target.'cfg(target_os = "macos")'.dependencies]
spudlib-sys = {path="../spudlib-sys", features = ["metal"]}