[package]
name = "spudlib-sys"
version = "0.1.0"
edition = "2021"
description = "Raw FFI bindings to the SpudLib C library"
license = "MIT"  # or whatever your license is
repository = "https://github.com/vigatel2717/spudlib"
links = "spudlib"  # tells Cargo only one crate can link this native lib

[build-dependencies]
cc = "1.0"
# only needed if you're doing Option 1 (bindgen at build time)
# bindgen = "0.70"

[features]
default = ["vulkan"]
vulkan = []
metal = []