
#include "spudcore.h"
#include <stddef.h>

#if __cplusplus
extern "C" {
#endif

#ifdef _DEBUG
void spud_debug_name_set(void *object, const char *name) {
	if (object) {
		/* Store the debug name in the first member of the object struct. */
		char **name_ptr = (char **)object;
		*name_ptr       = (char *)name;
	}
}

const char *spud_debug_name_get(void *object) {
	if (object) {
		/* Get the debug name from the first member of the object struct. */
		char **name_ptr = (char **)object;
		return *name_ptr;
	} else
		return NULL;
}
#endif // _DEBUG

const char *spudresult_str(SPUDRESULT r) {
	switch (r) {
	case SPUD_SUCCESS:
		return "SPUD_SUCCESS";
	case SPUDRESULT_GENERAL_FAILURE:
		return "SPUDRESULT_GENERAL_FAILURE";
	case SPUDRESULT_API_SPECIFIC_FAILURE:
		return "SPUDRESULT_API_SPECIFIC_FAILURE";
	case SPUDRESULT_INVALID_API:
		return "SPUDRESULT_INVALID_API";
	case SPUDRESULT_NULL_DESC:
		return "SPUDRESULT_NULL_DESC";
	case SPUDRESULT_NULL_OUTPUT_PARAMETER:
		return "SPUDRESULT_NULL_OUTPUT_PARAMETER";
	case SPUDRESULT_DESC_INVALID_PARAMETERS:
		return "SPUDRESULT_DESC_INVALID_PARAMETERS";
	case SPUDRESULT_INDEX_OUT_OF_RANGE:
		return "SPUDRESULT_INDEX_OUT_OF_RANGE";
	case SPUDRESULT_ZERO_SIZE:
		return "SPUDRESULT_ZERO_SIZE";
	case SPUDRESULT_OUT_OF_MEMORY:
		return "SPUDRESULT_OUT_OF_MEMORY";
	case SPUDRESULT_NOT_IMPLEMENTED_YET:
		return "SPUDRESULT_NOT_IMPLEMENTED_YET";
	case SPUDRESULT_GPU_DEVICE_ENUMERATION_FAILURE:
		return "SPUDRESULT_GPU_DEVICE_ENUMERATION_FAILURE";
	case SPUDRESULT_GPU_INVALID_INSTANCE:
		return "SPUDRESULT_GPU_INVALID_INSTANCE";
	case SPUDRESULT_GPU_INVALID_DEVICE:
		return "SPUDRESULT_GPU_INVALID_DEVICE";
	case SPUDRESULT_GPU_INVALID_COMMAND_QUEUE:
		return "SPUDRESULT_GPU_INVALID_COMMAND_QUEUE";
	case SPUDRESULT_GPU_INVALID_COMMAND_ALLOCATOR:
		return "SPUDRESULT_GPU_INVALID_COMMAND_ALLOCATOR";
	case SPUDRESULT_GPU_INVALID_COMMAND_LIST:
		return "SPUDRESULT_GPU_INVALID_COMMAND_LIST";
	case SPUDRESULT_GPU_INVALID_SWAP_CHAIN:
		return "SPUDRESULT_GPU_INVALID_SWAP_CHAIN";
	case SPUDRESULT_GPU_INVALID_SURFACE:
		return "SPUDRESULT_GPU_INVALID_SURFACE";
	case SPUDRESULT_GPU_INVALID_FORMAT:
		return "SPUDRESULT_GPU_INVALID_FORMAT";
	case SPUDRESULT_GPU_INVALID_WINDOW_HANDLE:
		return "SPUDRESULT_GPU_INVALID_WINDOW_HANDLE";
	case SPUDRESULT_GPU_INVALID_DISPLAY_HANDLE:
		return "SPUDRESULT_GPU_INVALID_DISPLAY_HANDLE";
	case SPUDRESULT_GPU_INVALID_COMMAND_LIST_TYPE:
		return "SPUDRESULT_GPU_INVALID_COMMAND_LIST_TYPE";
	case SPUDRESULT_GPU_INVALID_MEMORY_FLAGS:
		return "SPUDRESULT_GPU_INVALID_MEMORY_FLAGS";
	case SPUDRESULT_GPU_INVALID_BUFFER_USAGE:
		return "SPUDRESULT_GPU_INVALID_BUFFER_USAGE";
	case SPUDRESULT_GPU_INVALID_IMAGE_USAGE:
		return "SPUDRESULT_GPU_INVALID_IMAGE_USAGE";
	case SPUDRESULT_GPU_INVALID_BUFFER_STRIDE:
		return "SPUDRESULT_GPU_INVALID_BUFFER_STRIDE";
	case SPUDRESULT_GPU_INVALID_INDEX_STRIDE:
		return "SPUDRESULT_GPU_INVALID_INDEX_STRIDE";
	case SPUDRESULT_GPU_INVALID_BUFFER:
		return "SPUDRESULT_GPU_INVALID_BUFFER";
	case SPUDRESULT_GPU_INVALID_BUFFER_VIEW:
		return "SPUDRESULT_GPU_INVALID_BUFFER_VIEW";
	case SPUDRESULT_GPU_INVALID_IMAGE:
		return "SPUDRESULT_GPU_INVALID_IMAGE";
	case SPUDRESULT_GPU_INVALID_IMAGE_VIEW:
		return "SPUDRESULT_GPU_INVALID_IMAGE_VIEW";
	case SPUDRESULT_GPU_INVALID_IMAGE_VIEW_TYPE:
		return "SPUDRESULT_GPU_INVALID_IMAGE_VIEW_TYPE";
	case SPUDRESULT_GPU_INVALID_IMAGE_TYPE:
		return "SPUDRESULT_GPU_INVALID_IMAGE_TYPE";
	case SPUDRESULT_GPU_ZERO_BUFFER_SIZE:
		return "SPUDRESULT_GPU_ZERO_BUFFER_SIZE";
	case SPUDRESULT_GPU_INVALID_BUFFER_SIZE:
		return "SPUDRESULT_GPU_INVALID_BUFFER_SIZE";
	case SPUDRESULT_GPU_BUFFER_OR_IMAGE_VIEW_RANGE_OUT_OF_SCOPE:
		return "SPUDRESULT_GPU_BUFFER_OR_IMAGE_VIEW_RANGE_OUT_OF_SCOPE";
	case SPUDRESULT_GPU_MAP_OUT_OF_RANGE:
		return "SPUDRESULT_GPU_MAP_OUT_OF_RANGE";
	case SPUDRESULT_GPU_INVALID_SEMAPHORE:
		return "SPUDRESULT_GPU_INVALID_SEMAPHORE";
	case SPUDRESULT_GPU_INVALID_FENCE:
		return "SPUDRESULT_GPU_INVALID_FENCE";
	case SPUDRESULT_GPU_INVALID_SHADER_STAGE:
		return "SPUDRESULT_GPU_INVALID_SHADER_STAGE";
	case SPUDRESULT_GPU_INVALID_PRIMITIVE_TOPOLOGY:
		return "SPUDRESULT_GPU_INVALID_PRIMITIVE_TOPOLOGY";
	case SPUDRESULT_GPU_INVALID_CULL_MODE:
		return "SPUDRESULT_GPU_INVALID_CULL_MODE";
	case SPUDRESULT_GPU_INVALID_COMPARE_OP:
		return "SPUDRESULT_GPU_INVALID_COMPARE_OP";
	case SPUDRESULT_GPU_INVALID_BLEND_FACTOR:
		return "SPUDRESULT_GPU_INVALID_BLEND_FACTOR";
	case SPUDRESULT_GPU_INVALID_BLEND_OP:
		return "SPUDRESULT_GPU_INVALID_BLEND_OP";
	case SPUDRESULT_GPU_INVALID_SHADER_MODULE:
		return "SPUDRESULT_GPU_INVALID_SHADER_MODULE";
	case SPUDRESULT_GPU_INVALID_SHADER_PIPELINE:
		return "SPUDRESULT_GPU_INVALID_SHADER_PIPELINE";
	case SPUDRESULT_GPU_INVALID_COMPUTE_MODULE:
		return "SPUDRESULT_GPU_INVALID_COMPUTE_MODULE";
	case SPUDRESULT_GPU_INVALID_COMPUTE_PIPELINE:
		return "SPUDRESULT_GPU_INVALID_COMPUTE_PIPELINE";
	case SPUDRESULT_GPU_NULL_SPIRV:
		return "SPUDRESULT_GPU_NULL_SPIRV";
	case SPUDRESULT_GPU_INVALID_SPIRV_ALIGNMENT:
		return "SPUDRESULT_GPU_INVALID_SPIRV_ALIGNMENT";
	case SPUDRESULT_GPU_VERTEX_AND_FRAGMENT_SHADER_REQUIRED:
		return "SPUDRESULT_GPU_VERTEX_AND_FRAGMENT_SHADER_REQUIRED";
	case SPUDRESULT_GPU_SHADER_COMPILATION_FAILED:
		return "SPUDRESULT_GPU_SHADER_COMPILATION_FAILED";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_TYPE:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_TYPE";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_POOL_SIZE:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_POOL_SIZE";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_POOL:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_POOL";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_SET_LAYOUT:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_SET_LAYOUT";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_SET:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_SET";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_BUFFER_INFO:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_BUFFER_INFO";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_IMAGE_INFO:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_IMAGE_INFO";
	case SPUDRESULT_GPU_INVALID_WRITE_DESCRIPTOR_SET:
		return "SPUDRESULT_GPU_INVALID_WRITE_DESCRIPTOR_SET";
	case SPUDRESULT_GPU_TOO_MANY_DESCRIPTOR_BINDINGS:
		return "SPUDRESULT_GPU_TOO_MANY_DESCRIPTOR_BINDINGS";
	case SPUDRESULT_GPU_TOO_MANY_DESCRIPTOR_POOLS:
		return "SPUDRESULT_GPU_TOO_MANY_DESCRIPTOR_POOLS";
	case SPUDRESULT_GPU_ZERO_DESCRIPTOR_SET_LAYOUTS:
		return "SPUDRESULT_GPU_ZERO_DESCRIPTOR_SET_LAYOUTS";
	case SPUDRESULT_GPU_TOO_MANY_DESCRIPTOR_SET_LAYOUTS:
		return "SPUDRESULT_GPU_TOO_MANY_DESCRIPTOR_SET_LAYOUTS";
	case SPUDRESULT_GPU_INTERNAL_DESCRIPTOR_SET_ALLOCATION_FAIL:
		return "SPUDRESULT_GPU_INTERNAL_DESCRIPTOR_SET_ALLOCATION_FAIL";
	case SPUDRESULT_GPU_CANNOT_RESOLVE_API_SPECIFIC_DESCRIPTOR_TYPE:
		return "SPUDRESULT_GPU_CANNOT_RESOLVE_API_SPECIFIC_DESCRIPTOR_TYPE";
	case SPUDRESULT_GPU_BINDLESS_OUT_OF_SLOTS:
		return "SPUDRESULT_GPU_BINDLESS_OUT_OF_SLOTS";
	case SPUDRESULT_GPU_EXT_BINDLESS_DESCRIPTOR_INDEXING_NOT_SUPPORTED:
		return "SPUDRESULT_GPU_EXT_BINDLESS_DESCRIPTOR_INDEXING_NOT_SUPPORTED";
	case SPUDRESULT_GPU_EXT_MESH_SHADING_NOT_SUPPORTED:
		return "SPUDRESULT_GPU_EXT_MESH_SHADING_NOT_SUPPORTED";
	case SPUDRESULT_GPU_EXT_DEPTH_BOUNDS_TEST_NOT_SUPPORTED:
		return "SPUDRESULT_GPU_EXT_DEPTH_BOUNDS_TEST_NOT_SUPPORTED";
	case SPUDRESULT_GPU_INVALID_RESOURCE_STATE:
		return "SPUDRESULT_GPU_INVALID_RESOURCE_STATE";
	case SPUDRESULT_GPU_INVALID_IMAGE_LAYOUT:
		return "SPUDRESULT_GPU_INVALID_IMAGE_LAYOUT";
	case SPUDRESULT_GPU_INVALID_PIPELINE_STAGE:
		return "SPUDRESULT_GPU_INVALID_PIPELINE_STAGE";
	case SPUDRESULT_GPU_INVALID_BUFFER_BARRIER:
		return "SPUDRESULT_GPU_INVALID_BUFFER_BARRIER";
	case SPUDRESULT_GPU_INVALID_IMAGE_BARRIER:
		return "SPUDRESULT_GPU_INVALID_IMAGE_BARRIER";
	case SPUDRESULT_SFS_NULL_PATH:
		return "SPUDRESULT_SFS_NULL_PATH";
	case SPUDRESULT_SFS_INVALID_FILE:
		return "SPUDRESULT_SFS_INVALID_FILE";
	case SPUDRESULT_SMEM_ZERO_CAPACITY:
		return "SPUDRESULT_SMEM_ZERO_CAPACITY";
	case SPUDRESULT_SMEM_INSUFFICIENT_CAPACITY:
		return "SPUDRESULT_SMEM_INSUFFICIENT_CAPACITY";
	case SPUDRESULT_SMEM_PLAT_COMMIT_FAIL:
		return "SPUDRESULT_SMEM_PLAT_COMMIT_FAIL";
	case SPUDRESULT_SMEM_INVALID_ARENA:
		return "SPUDRESULT_SMEM_INVALID_ARENA";
	case SPUDRESULT_SNET_STARTUP_FAILED:
		return "SPUDRESULT_SNET_STARTUP_FAILED";
	case SPUDRESULT_SNET_INVALID_SOCKET:
		return "SPUDRESULT_SNET_INVALID_SOCKET";
	case SPUDRESULT_SNET_RESOLVE_FAILED:
		return "SPUDRESULT_SNET_RESOLVE_FAILED";
	case SPUDRESULT_SNET_CONNECT_FAILED:
		return "SPUDRESULT_SNET_CONNECT_FAILED";
	case SPUDRESULT_SNET_LISTEN_FAILED:
		return "SPUDRESULT_SNET_LISTEN_FAILED";
	case SPUDRESULT_SNET_ACCEPT_FAILED:
		return "SPUDRESULT_SNET_ACCEPT_FAILED";
	case SPUDRESULT_SNET_SEND_FAILED:
		return "SPUDRESULT_SNET_SEND_FAILED";
	case SPUDRESULT_SNET_RECV_FAILED:
		return "SPUDRESULT_SNET_RECV_FAILED";
	case SPUDRESULT_SNET_WOULD_BLOCK:
		return "SPUDRESULT_SNET_WOULD_BLOCK";
	case SPUDRESULT_SNET_SET_BLOCKING_FAILED:
		return "SPUDRESULT_SNET_SET_BLOCKING_FAILED";
	case SPUDRESULT_SAUD_INVALID_INSTANCE:
		return "SPUDRESULT_SAUD_INVALID_INSTANCE";
	case SPUDRESULT_SAUD_INVALID_DEVICE:
		return "SPUDRESULT_SAUD_INVALID_DEVICE";
	case SPUDRESULT_SAUD_INVALID_STREAM:
		return "SPUDRESULT_SAUD_INVALID_STREAM";
	case SPUDRESULT_SAUD_FORMAT_NOT_SUPPORTED:
		return "SPUDRESULT_SAUD_FORMAT_NOT_SUPPORTED";
	case SPUDRESULT_SAUD_EXCLUSIVE_UNAVAILABLE:
		return "SPUDRESULT_SAUD_EXCLUSIVE_UNAVAILABLE";
	case SPUDRESULT_SAUD_DEVICE_LOST:
		return "SPUDRESULT_SAUD_DEVICE_LOST";
	case SPUDRESULT_SAUD_PERIOD_OUT_OF_RANGE:
		return "SPUDRESULT_SAUD_PERIOD_OUT_OF_RANGE";
	case SPUDRESULT_SAUD_BUFFER_OUT_OF_RANGE:
		return "SPUDRESULT_SAUD_BUFFER_OUT_OF_RANGE";
	case SPUDRESULT_SAUD_THREAD_PRIORITY_UNSUPPORTED:
		return "SPUDRESULT_SAUD_THREAD_PRIORITY_UNSUPPORTED";
	case SPUDRESULT_SAUD_THREAD_PRIORITY_DENIED:
		return "SPUDRESULT_SAUD_THREAD_PRIORITY_DENIED";
	case SPUDRESULT_SAUD_SAMPLE_RATE_NOT_SETTABLE:
		return "SPUDRESULT_SAUD_SAMPLE_RATE_NOT_SETTABLE";
	case SPUDRESULT_SAUD_OS_CONVERSION_UNAVAILABLE:
		return "SPUDRESULT_SAUD_OS_CONVERSION_UNAVAILABLE";
	default:
		return "SPUDRESULT_UNKNOWN";
	}
}

#if __cplusplus
}
#endif
