
#include "spudcore.h"
#include "stddef.h"

#if __cplusplus
extern "C" {
#endif

#ifdef _DEBUG
void spud_debug_name_set(void *object, const char *name) {
	if (object) {
		/* Store the debug name in the first member of the object struct. */
		char **name_ptr = (char **)object;
		*name_ptr       = (char *)name;
	}
}

const char *spud_debug_name_get(void *object) {
	if (object) {
		/* Get the debug name from the first member of the object struct. */
		char **name_ptr = (char **)object;
		return *name_ptr;
	} else
		return NULL;
}
#endif // _DEBUG

const char *spudresult_str(SPUDRESULT r) {
	switch (r) {
	case SPUD_SUCCESS:
		return "SPUD_SUCCESS";
	case SPUDRESULT_GENERAL_FAILURE:
		return "SPUDRESULT_GENERAL_FAILURE";
	case SPUDRESULT_API_SPECIFIC_FAILURE:
		return "SPUDRESULT_API_SPECIFIC_FAILURE";
	case SPUDRESULT_INVALID_API:
		return "SPUDRESULT_INVALID_API";
	case SPUDRESULT_NULL_DESC:
		return "SPUDRESULT_NULL_DESC";
	case SPUDRESULT_DESC_INVALID_PARAMETERS:
		return "SPUDRESULT_DESC_INVALID_PARAMETERS";
	case SPUDRESULT_GPU_DEVICE_ENUMERATION_FAILURE:
		return "SPUDRESULT_GPU_DEVICE_ENUMERATION_FAILURE";
	case SPUDRESULT_GPU_INVALID_INSTANCE:
		return "SPUDRESULT_GPU_INVALID_INSTANCE";
	case SPUDRESULT_GPU_INVALID_DEVICE:
		return "SPUDRESULT_GPU_INVALID_DEVICE";
	case SPUDRESULT_GPU_INVALID_COMMAND_QUEUE:
		return "SPUDRESULT_GPU_INVALID_COMMAND_QUEUE";
	case SPUDRESULT_GPU_INVALID_COMMAND_ALLOCATOR:
		return "SPUDRESULT_GPU_INVALID_COMMAND_ALLOCATOR";
	case SPUDRESULT_GPU_INVALID_COMMAND_LIST:
		return "SPUDRESULT_GPU_INVALID_COMMAND_LIST";
	case SPUDRESULT_GPU_INVALID_SWAP_CHAIN:
		return "SPUDRESULT_GPU_INVALID_SWAP_CHAIN";
	case SPUDRESULT_GPU_INVALID_SURFACE:
		return "SPUDRESULT_GPU_INVALID_SURFACE";
	case SPUDRESULT_GPU_INVALID_FORMAT:
		return "SPUDRESULT_GPU_INVALID_FORMAT";
	case SPUDRESULT_GPU_INVALID_WINDOW_HANDLE:
		return "SPUDRESULT_GPU_INVALID_WINDOW_HANDLE";
	case SPUDRESULT_GPU_INVALID_DISPLAY_HANDLE:
		return "SPUDRESULT_GPU_INVALID_DISPLAY_HANDLE";
	case SPUDRESULT_GPU_INVALID_MEMORY_FLAGS:
		return "SPUDRESULT_GPU_INVALID_MEMORY_FLAGS";
	case SPUDRESULT_GPU_INVALID_BUFFER_USAGE:
		return "SPUDRESULT_GPU_INVALID_BUFFER_USAGE";
	case SPUDRESULT_GPU_INVALID_IMAGE_USAGE:
		return "SPUDRESULT_GPU_INVALID_IMAGE_USAGE";
	case SPUDRESULT_GPU_INVALID_BUFFER:
		return "SPUDRESULT_GPU_INVALID_BUFFER";
	case SPUDRESULT_GPU_INVALID_BUFFER_VIEW:
		return "SPUDRESULT_GPU_INVALID_BUFFER_VIEW";
	case SPUDRESULT_GPU_INVALID_IMAGE:
		return "SPUDRESULT_GPU_INVALID_IMAGE";
	case SPUDRESULT_GPU_INVALID_IMAGE_VIEW:
		return "SPUDRESULT_GPU_INVALID_IMAGE_VIEW";
	case SPUDRESULT_GPU_INVALID_IMAGE_VIEW_TYPE:
		return "SPUDRESULT_GPU_INVALID_IMAGE_VIEW_TYPE";
	case SPUDRESULT_GPU_ZERO_BUFFER_SIZE:
		return "SPUDRESULT_GPU_ZERO_BUFFER_SIZE";
	/* SPUDRESULT_GPU_INVALID_BUFFER_SIZE shares value 235 with
	 * SPUDRESULT_GPU_ZERO_BUFFER_SIZE */
	case SPUDRESULT_GPU_BUFFER_OR_IMAGE_VIEW_RANGE_OUT_OF_SCOPE:
		return "SPUDRESULT_GPU_BUFFER_OR_IMAGE_VIEW_RANGE_OUT_OF_SCOPE";
	case SPUDRESULT_GPU_MAP_OUT_OF_RANGE:
		return "SPUDRESULT_GPU_MAP_OUT_OF_RANGE";
	case SPUDRESULT_GPU_INVALID_SEMAPHORE:
		return "SPUDRESULT_GPU_INVALID_SEMAPHORE";
	case SPUDRESULT_GPU_INVALID_FENCE:
		return "SPUDRESULT_GPU_INVALID_FENCE";
	case SPUDRESULT_GPU_INVALID_SHADER_STAGE:
		return "SPUDRESULT_GPU_INVALID_SHADER_STAGE";
	case SPUDRESULT_GPU_INVALID_PRIMITIVE_TOPOLOGY:
		return "SPUDRESULT_GPU_INVALID_PRIMITIVE_TOPOLOGY";
	case SPUDRESULT_GPU_INVALID_CULL_MODE:
		return "SPUDRESULT_GPU_INVALID_CULL_MODE";
	case SPUDRESULT_GPU_INVALID_COMPARE_OP:
		return "SPUDRESULT_GPU_INVALID_COMPARE_OP";
	case SPUDRESULT_GPU_INVALID_BLEND_FACTOR:
		return "SPUDRESULT_GPU_INVALID_BLEND_FACTOR";
	case SPUDRESULT_GPU_INVALID_BLEND_OP:
		return "SPUDRESULT_GPU_INVALID_BLEND_OP";
	case SPUDRESULT_GPU_INVALID_SHADER_MODULE:
		return "SPUDRESULT_GPU_INVALID_SHADER_MODULE";
	case SPUDRESULT_GPU_INVALID_SHADER_PIPELINE:
		return "SPUDRESULT_GPU_INVALID_SHADER_PIPELINE";
	case SPUDRESULT_GPU_INVALID_COMPUTE_PIPELINE:
		return "SPUDRESULT_GPU_INVALID_COMPUTE_PIPELINE";
	case SPUDRESULT_GPU_NULL_SPIRV:
		return "SPUDRESULT_GPU_NULL_SPIRV";
	case SPUDRESULT_GPU_INVALID_SPIRV_ALIGNMENT:
		return "SPUDRESULT_GPU_INVALID_SPIRV_ALIGNMENT";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_TYPE:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_TYPE";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_POOL_SIZE:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_POOL_SIZE";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_POOL:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_POOL";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_SET_LAYOUT:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_SET_LAYOUT";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_SET:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_SET";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_BUFFER_INFO:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_BUFFER_INFO";
	case SPUDRESULT_GPU_INVALID_DESCRIPTOR_IMAGE_INFO:
		return "SPUDRESULT_GPU_INVALID_DESCRIPTOR_IMAGE_INFO";
	case SPUDRESULT_GPU_INVALID_WRITE_DESCRIPTOR_SET:
		return "SPUDRESULT_GPU_INVALID_WRITE_DESCRIPTOR_SET";
	case SPUDRESULT_GPU_INVALID_RESOURCE_STATE:
		return "SPUDRESULT_GPU_INVALID_RESOURCE_STATE";
	case SPUDRESULT_GPU_INVALID_IMAGE_LAYOUT:
		return "SPUDRESULT_GPU_INVALID_IMAGE_LAYOUT";
	case SPUDRESULT_GPU_INVALID_PIPELINE_STAGE:
		return "SPUDRESULT_GPU_INVALID_PIPELINE_STAGE";
	case SPUDRESULT_GPU_INVALID_BUFFER_BARRIER:
		return "SPUDRESULT_GPU_INVALID_BUFFER_BARRIER";
	case SPUDRESULT_GPU_INVALID_IMAGE_BARRIER:
		return "SPUDRESULT_GPU_INVALID_IMAGE_BARRIER";
	default:
		return "SPUDRESULT_UNKNOWN";
	}
}

#if __cplusplus
}
#endif
