
#include "spudgpu.h"

#if __cplusplus
extern "C" {
#endif

/* Bits-per-pixel table. Values match Microsoft's published DXGI_FORMAT bit
 * depths (SPUDGPU_FORMAT is numerically identical to DXGI_FORMAT — see
 * spudgpu_d3d12_get_dxgi_format). Block-compressed formats (BC1-7) report
 * their average bits-per-pixel (block byte size * 8 / 16 texels per block),
 * matching how DirectXTex's BitsPerPixel() reports them. */
uint32_t spudgpu_format_bit_count(SPUDGPU_FORMAT fmt) {
	switch (fmt) {
	case SPUDGPU_FORMAT_UNKNOWN:
		return 0;

	case SPUDGPU_FORMAT_R32G32B32A32_TYPELESS:
	case SPUDGPU_FORMAT_R32G32B32A32_FLOAT:
	case SPUDGPU_FORMAT_R32G32B32A32_UINT:
	case SPUDGPU_FORMAT_R32G32B32A32_SINT:
		return 128;

	case SPUDGPU_FORMAT_R32G32B32_TYPELESS:
	case SPUDGPU_FORMAT_R32G32B32_FLOAT:
	case SPUDGPU_FORMAT_R32G32B32_UINT:
	case SPUDGPU_FORMAT_R32G32B32_SINT:
		return 96;

	case SPUDGPU_FORMAT_R16G16B16A16_TYPELESS:
	case SPUDGPU_FORMAT_R16G16B16A16_FLOAT:
	case SPUDGPU_FORMAT_R16G16B16A16_UNORM:
	case SPUDGPU_FORMAT_R16G16B16A16_UINT:
	case SPUDGPU_FORMAT_R16G16B16A16_SNORM:
	case SPUDGPU_FORMAT_R16G16B16A16_SINT:
	case SPUDGPU_FORMAT_R32G32_TYPELESS:
	case SPUDGPU_FORMAT_R32G32_FLOAT:
	case SPUDGPU_FORMAT_R32G32_UINT:
	case SPUDGPU_FORMAT_R32G32_SINT:
	case SPUDGPU_FORMAT_R32G8X24_TYPELESS:
	case SPUDGPU_FORMAT_D32_FLOAT_S8X24_UINT:
	case SPUDGPU_FORMAT_R32_FLOAT_X8X24_TYPELESS:
	case SPUDGPU_FORMAT_X32_TYPELESS_G8X24_UINT:
	case SPUDGPU_FORMAT_Y416:
	case SPUDGPU_FORMAT_Y210:
	case SPUDGPU_FORMAT_Y216:
		return 64;

	case SPUDGPU_FORMAT_R10G10B10A2_TYPELESS:
	case SPUDGPU_FORMAT_R10G10B10A2_UNORM:
	case SPUDGPU_FORMAT_R10G10B10A2_UINT:
	case SPUDGPU_FORMAT_R11G11B10_FLOAT:
	case SPUDGPU_FORMAT_R8G8B8A8_TYPELESS:
	case SPUDGPU_FORMAT_R8G8B8A8_UNORM:
	case SPUDGPU_FORMAT_R8G8B8A8_UNORM_SRGB:
	case SPUDGPU_FORMAT_R8G8B8A8_UINT:
	case SPUDGPU_FORMAT_R8G8B8A8_SNORM:
	case SPUDGPU_FORMAT_R8G8B8A8_SINT:
	case SPUDGPU_FORMAT_R16G16_TYPELESS:
	case SPUDGPU_FORMAT_R16G16_FLOAT:
	case SPUDGPU_FORMAT_R16G16_UNORM:
	case SPUDGPU_FORMAT_R16G16_UINT:
	case SPUDGPU_FORMAT_R16G16_SNORM:
	case SPUDGPU_FORMAT_R16G16_SINT:
	case SPUDGPU_FORMAT_R32_TYPELESS:
	case SPUDGPU_FORMAT_D32_FLOAT:
	case SPUDGPU_FORMAT_R32_FLOAT:
	case SPUDGPU_FORMAT_R32_UINT:
	case SPUDGPU_FORMAT_R32_SINT:
	case SPUDGPU_FORMAT_R24G8_TYPELESS:
	case SPUDGPU_FORMAT_D24_UNORM_S8_UINT:
	case SPUDGPU_FORMAT_R24_UNORM_X8_TYPELESS:
	case SPUDGPU_FORMAT_X24_TYPELESS_G8_UINT:
	case SPUDGPU_FORMAT_R9G9B9E5_SHAREDEXP:
	case SPUDGPU_FORMAT_R8G8_B8G8_UNORM:
	case SPUDGPU_FORMAT_G8R8_G8B8_UNORM:
	case SPUDGPU_FORMAT_B8G8R8A8_UNORM:
	case SPUDGPU_FORMAT_B8G8R8X8_UNORM:
	case SPUDGPU_FORMAT_R10G10B10_XR_BIAS_A2_UNORM:
	case SPUDGPU_FORMAT_B8G8R8A8_TYPELESS:
	case SPUDGPU_FORMAT_B8G8R8A8_UNORM_SRGB:
	case SPUDGPU_FORMAT_B8G8R8X8_TYPELESS:
	case SPUDGPU_FORMAT_B8G8R8X8_UNORM_SRGB:
	case SPUDGPU_FORMAT_AYUV:
	case SPUDGPU_FORMAT_Y410:
		return 32;

	case SPUDGPU_FORMAT_R8G8_TYPELESS:
	case SPUDGPU_FORMAT_R8G8_UNORM:
	case SPUDGPU_FORMAT_R8G8_UINT:
	case SPUDGPU_FORMAT_R8G8_SNORM:
	case SPUDGPU_FORMAT_R8G8_SINT:
	case SPUDGPU_FORMAT_R16_TYPELESS:
	case SPUDGPU_FORMAT_R16_FLOAT:
	case SPUDGPU_FORMAT_D16_UNORM:
	case SPUDGPU_FORMAT_R16_UNORM:
	case SPUDGPU_FORMAT_R16_UINT:
	case SPUDGPU_FORMAT_R16_SNORM:
	case SPUDGPU_FORMAT_R16_SINT:
	case SPUDGPU_FORMAT_B5G6R5_UNORM:
	case SPUDGPU_FORMAT_B5G5R5A1_UNORM:
	case SPUDGPU_FORMAT_B4G4R4A4_UNORM:
	case SPUDGPU_FORMAT_YUY2:
	case SPUDGPU_FORMAT_A8P8:
		return 16;

	case SPUDGPU_FORMAT_R8_TYPELESS:
	case SPUDGPU_FORMAT_R8_UNORM:
	case SPUDGPU_FORMAT_R8_UINT:
	case SPUDGPU_FORMAT_R8_SNORM:
	case SPUDGPU_FORMAT_R8_SINT:
	case SPUDGPU_FORMAT_A8_UNORM:
	case SPUDGPU_FORMAT_AI44:
	case SPUDGPU_FORMAT_IA44:
	case SPUDGPU_FORMAT_P8:
	case SPUDGPU_FORMAT_NV12:
	case SPUDGPU_FORMAT_420_OPAQUE:
	case SPUDGPU_FORMAT_NV11:
		return 8; /* NV12/420_OPAQUE/NV11 are 4:2:0 planar — 8bpp Y plane average, matching DXGI's reported value */

	case SPUDGPU_FORMAT_P010:
	case SPUDGPU_FORMAT_P016:
		return 24;

	case SPUDGPU_FORMAT_R1_UNORM:
		return 1;

	/* Block-compressed formats: average bits per pixel (bytes-per-block * 8 / 16 texels). */
	case SPUDGPU_FORMAT_BC1_TYPELESS:
	case SPUDGPU_FORMAT_BC1_UNORM:
	case SPUDGPU_FORMAT_BC1_UNORM_SRGB:
	case SPUDGPU_FORMAT_BC4_TYPELESS:
	case SPUDGPU_FORMAT_BC4_UNORM:
	case SPUDGPU_FORMAT_BC4_SNORM:
		return 4;

	case SPUDGPU_FORMAT_BC2_TYPELESS:
	case SPUDGPU_FORMAT_BC2_UNORM:
	case SPUDGPU_FORMAT_BC2_UNORM_SRGB:
	case SPUDGPU_FORMAT_BC3_TYPELESS:
	case SPUDGPU_FORMAT_BC3_UNORM:
	case SPUDGPU_FORMAT_BC3_UNORM_SRGB:
	case SPUDGPU_FORMAT_BC5_TYPELESS:
	case SPUDGPU_FORMAT_BC5_UNORM:
	case SPUDGPU_FORMAT_BC5_SNORM:
	case SPUDGPU_FORMAT_BC6H_TYPELESS:
	case SPUDGPU_FORMAT_BC6H_UF16:
	case SPUDGPU_FORMAT_BC6H_SF16:
	case SPUDGPU_FORMAT_BC7_TYPELESS:
	case SPUDGPU_FORMAT_BC7_UNORM:
	case SPUDGPU_FORMAT_BC7_UNORM_SRGB:
		return 8;

	/* Legacy/rare formats with no well-established bpp convention. */
	case SPUDGPU_FORMAT_P208:
	case SPUDGPU_FORMAT_V208:
	case SPUDGPU_FORMAT_V408:
	default:
		return 0;
	}
}

#if __cplusplus
}
#endif
